version: '3.1'
services:
  baton-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: baton
      MYSQL_USER: baton
      MYSQL_PASSWORD: baton
    platform: linux/x86_64