spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/baton
    username: root
    password: baton
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: depromeet.batonsearch.global.config.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET}
      prefix: ${AWS_FOLDER}
    stack:
      auto: false