server:
  error:
    include-message: always
    whitelabel.enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  profiles:
    active: prod
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false