spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/./testdb
    username: testdb
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
